"""Remove BVN Requirements

Revision ID: 7a99ee5f337b
Revises: 733277fc6be3
Create Date: 2026-05-13 11:19:47.963096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a99ee5f337b'
down_revision: Union[str, Sequence[str], None] = '733277fc6be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('account_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'bvn_hash')
    op.drop_column('users', 'bvn_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bvn_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('bvn_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'account_verified')
    op.drop_column('profiles', 'updated_at')
    op.create_table(
        'wallets',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('balance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
        sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False
        ),
        sa.Column(
            'updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wallets_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('wallets_pkey')),
        sa.UniqueConstraint(
            'user_id', name=op.f('wallets_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    # ### end Alembic commands ###
