"""Improved Wallets

Revision ID: 6a818628e656
Revises: d4e72fa29198
Create Date: 2026-05-14 14:59:08.497735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a818628e656'
down_revision: Union[str, Sequence[str], None] = 'd4e72fa29198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_fundings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('squad_transaction_ref', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_fundings_reference'), 'wallet_fundings', ['reference'], unique=True)
    op.create_index(op.f('ix_wallet_fundings_status'), 'wallet_fundings', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_fundings_user_id'), 'wallet_fundings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_fundings_user_id'), table_name='wallet_fundings')
    op.drop_index(op.f('ix_wallet_fundings_status'), table_name='wallet_fundings')
    op.drop_index(op.f('ix_wallet_fundings_reference'), table_name='wallet_fundings')
    op.drop_table('wallet_fundings')
    # ### end Alembic commands ###
