"""User registration

Revision ID: 733277fc6be3
Revises: d90b3acf94fb
Create Date: 2026-05-12 18:36:06.585634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733277fc6be3'
down_revision: Union[str, Sequence[str], None] = 'd90b3acf94fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.String(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('users', sa.Column('bvn_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('account_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('bank_code', sa.String(), nullable=False))
    op.add_column('users', sa.Column('geo_lat', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('geo_lng', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'geo_lng')
    op.drop_column('users', 'geo_lat')
    op.drop_column('users', 'bank_code')
    op.drop_column('users', 'account_number')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'bvn_hash')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'address')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'email')
    op.drop_table('wallets')
    # ### end Alembic commands ###
