services:
  api:
    depends_on:
      - database
    container_name: saabi-api
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload --log-level debug
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    restart: on-failure

  worker:
    depends_on:
      - redis
    container_name: saabi-api-worker
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    restart: on-failure

  redis:
    container_name: saabi-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  database:
    container_name: saabi-postgres
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data:
  redis_data:
